name: Code build and review 
on: push 
jobs:
 CICDjob:
  env:
   imagename: "myjavaapp"
  runs-on: ubuntu-latest
  steps:
  - name: Clone the current repository on the runner
    uses: actions/checkout@v4
  - name: Setup Java 17 and maven 
    uses: actions/setup-java@v4
    with:
     distribution: 'temurin'
     java-version: '17'
     cache: 'maven'
  - name: Build the Maven 
    run: mvn package 
  - name: Install docker
    uses: docker/setup-docker-action@v4
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }
  - name: Build and push
    uses: docker/build-push-action@v6
    with:
        context: .
        push: true
        tags: ${{ DOCKERHUB_USERNAME }}/${{ env.imageName }}:latest
  - name: Deploy the Image
    run: |
     docker run -d -P ${{ DOCKERHUB_USERNAME }}/${{ env.imageName }}:latest
     docker ps -a
